### ISSUE TITLE
Make Truffle build artifacts directory configurable.

### ISSUE THREAD

**Issue by nfurfaro** [MedXProtocol/zos-truffle-merge#1]
As this project is meant for use with truffle, it would make sense for it to read from the `truffle.js` file to see if a build directory other than the default has been set and if so then use it rather than writing to the `/build/contracts/` directory. 
If no alternate build directory is specified in `truffle.js` then default to `/build/contracts` just like truffle.

**Comment by asselstine** [comment]
I like it!  Let's make it happen.

Two steps:

- [ ] Make artifacts directory configurable
- [ ] Have the script automagically pull in the artifacts directory from `truffle.js`

**Comment by asselstine** [comment]
This is now implemented
